In [1]:
import numpy as np
np.random.seed(1234)  # This makes sure that random is not random...

# Indexing, Slicing, etc

In [2]:
# Let's create a 7x7 array
s_by_s = np.arange(49).reshape((7,7))
print(s_by_s)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]


In [22]:
# Write Code to extract ...
# rows starting with [14 ...] and [21 ...]

rows_14_and_21 = s_by_s[s_by_s[0].any() == 14 or 21]

print(rows_14_and_21)
# every second columns starting from 2


IndexError: index 21 is out of bounds for axis 0 with size 7

# Functions in Numpy

In [ ]:
# construct a 2D  array
twenty_ints = np.linspace(0,95, 20, dtype=np.int8)
twoD_arr = twenty_ints.reshape(4, -1)
print(twoD_arr)

In [ ]:
print(twoD_arr.mean())  # mean of all

In [ ]:
print(twoD_arr.mean(axis=0))  # means of columns

In [ ]:
print(twoD_arr.mean(axis=1))  # means of rows

# Filters...

In [ ]:
filter = twoD_arr < 50
print(filter)

In [ ]:
# Update where filtered:

# Combine the two

In [ ]:
np.random.seed(12345)
practice = np.random.rand(4, 5)
practice

In [ ]:
# Calculate the column-wise **sum** of every second column


In [ ]:
# Compute the minimum of every row


In [ ]:
# Compute the absolute minimum


In [ ]:
# Set the cells that are larger than 0.8 to 1
